// Generated by CoffeeScript 1.3.3
var Converters, Packet, fromBuffer, sprintf, toBuffer, utils;

sprintf = require('./../support/sprintf');

utils = require('./utils');

Converters = require('./packet/converters');

String.prototype.stripBinNull = function() {
  var pos;
  pos = this.indexOf('\u0000');
  if (pos === -1) {
    return this;
  } else {
    return this.substr(0, pos);
  }
};

fromBuffer = function(b) {
  var i, optLen, optNum, optVal, options, ret, _ref;
  ret = {
    op: b[0],
    htype: b[1],
    hlen: b.readUInt8(2),
    hops: b.readUInt8(3),
    xid: b.readUInt32BE(4),
    secs: b.readUInt16BE(8),
    flags: b.readUInt16BE(10),
    ciaddr: utils.readIp(b, 12),
    yiaddr: utils.readIp(b, 16),
    siaddr: utils.readIp(b, 20),
    giaddr: utils.readIp(b, 24),
    chaddr: utils.readMacAddress(b.slice(28, 28 + b.readUInt8(2))),
    sname: b.toString('ascii', 44, 108).stripBinNull(),
    file: b.toString('ascii', 108, 236).stripBinNull(),
    options: {}
  };
  _ref = [0, b.slice(240)], i = _ref[0], options = _ref[1];
  while (i < options.length && options[i] !== 255) {
    optNum = parseInt(options[i++], 10);
    optLen = parseInt(options[i++], 10);
    optVal = Converters.get(optNum).decode(options.slice(i, i + optLen));
    ret.options[optNum] = optVal;
    i += optLen;
  }
  return new Packet(ret);
};

toBuffer = function() {
  var buffer, hex, i, key, octet, opt, padded, pos, value, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1, _ref2, _ref3;
  buffer = new Buffer(512, 'ascii');
  pos = 0;
  buffer[pos++] = this.op;
  buffer[pos++] = this.htype;
  buffer.writeUInt8(this.hlen, 2);
  buffer.writeUInt8(this.hops, 3);
  buffer.writeUInt32BE(this.xid, 4);
  buffer.writeUInt16BE(this.secs, 8);
  buffer.writeUInt16BE(this.flags, 10);
  pos = 12;
  _ref = ["ciaddr", "yiaddr", "siaddr", "giaddr"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    key = _ref[_i];
    _ref1 = (this[key] || "0.0.0.0").split(".");
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      octet = _ref1[_j];
      buffer.writeUInt8(parseInt(octet, 10), pos++);
    }
  }
  _ref2 = this.chaddr.split(':');
  for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
    hex = _ref2[_k];
    buffer[pos++] = parseInt(hex, 16);
  }
  buffer.fill(0, pos, 235);
  pos = 236;
  _ref3 = [99, 130, 83, 99];
  for (_l = 0, _len3 = _ref3.length; _l < _len3; _l++) {
    i = _ref3[_l];
    buffer[pos++] = i;
  }
  pos = 240;
  for (opt in this.options) {
    value = this.options[opt];
    pos = Converters.get(opt).encode(buffer, opt, value, pos);
  }
  buffer[pos] = 255;
  padded = new Buffer(pos, 'ascii');
  buffer.copy(padded, 0, 0, pos);
  return padded;
};

Packet = (function() {

  Packet.fromBuffer = fromBuffer;

  function Packet(array) {
    var key;
    for (key in array) {
      this[key] = array[key];
    }
  }

  Packet.prototype.toBuffer = toBuffer;

  Packet.prototype.op = function(op) {
    this.op = op;
    return this;
  };

  Packet.prototype.htype = function(htype) {
    this.htype = htype;
    return this;
  };

  Packet.prototype.hlen = function(hlen) {
    this.hlen = hlen;
    return this;
  };

  Packet.prototype.hops = function(hops) {
    this.hops = hops;
    return this;
  };

  Packet.prototype.xid = function(xid) {
    this.xid = xid;
    return this;
  };

  Packet.prototype.secs = function(secs) {
    this.secs = secs;
    return this;
  };

  Packet.prototype.flags = function(flags) {
    this.flags = flags;
    return this;
  };

  Packet.prototype.ciaddr = function(ciaddr) {
    this.ciaddr = ciaddr != null ? ciaddr : '0.0.0.0';
    return this;
  };

  Packet.prototype.yiaddr = function(yiaddr) {
    this.yiaddr = yiaddr != null ? yiaddr : '0.0.0.0';
    return this;
  };

  Packet.prototype.siaddr = function(siaddr) {
    this.siaddr = siaddr != null ? siaddr : '0.0.0.0';
    return this;
  };

  Packet.prototype.giaddr = function(giaddr) {
    this.giaddr = giaddr != null ? giaddr : '0.0.0.0';
    return this;
  };

  Packet.prototype.chaddr = function(chaddr) {
    this.chaddr = chaddr;
    return this;
  };

  Packet.prototype.sname = function(sname) {
    this.sname = sname;
    return this;
  };

  Packet.prototype.file = function(file) {
    this.file = file;
    return this;
  };

  Packet.prototype.options = function(options) {
    this.options = options;
    return this;
  };

  return Packet;

})();

module.exports = {
  Packet: Packet,
  fromBuffer: fromBuffer,
  toBuffer: toBuffer
};
